config/routes.rb
Ashop::Application.routes.draw do
  resources :product_types

  resources :comments

  resources :prices

  resources :order_items

  resources :deliveries

  resources :ordered_products

  resources :sellers

  resources :incomming_orders

  resources :orders

  resources :customers

  resources :products

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment_id, :description, :product_id, :rating, :subject, :user_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :receiver_id, :state
end

app/models/incomming_order.rb
class IncommingOrder < ActiveRecord::Base
  attr_accessible :seller_id
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :description, :user_id
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :order_id, :position, :product_id
end

app/models/ordered_product.rb
class OrderedProduct < ActiveRecord::Base
  attr_accessible :name, :order_id
end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :active, :position, :price, :product_id
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :name, :parent_id, :position
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  attr_accessible :address, :name, :phone
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_types }
    end
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/new
  # GET /product_types/new.json
  def new
    @product_type = ProductType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/1/edit
  def edit
    @product_type = ProductType.find(params[:id])
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(params[:product_type])

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render json: @product_type, status: :created, location: @product_type }
      else
        format.html { render action: "new" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_types/1
  # PUT /product_types/1.json
  def update
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      if @product_type.update_attributes(params[:product_type])
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type = ProductType.find(params[:id])
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing product_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<h1>Listing product_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Parent</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_types.each do |product_type| %>
  <tr>
    <td><%= product_type.name %></td>
    <td><%= product_type.parent_id %></td>
    <td><%= product_type.position %></td>
    <td><%= link_to 'Show', product_type %></td>
    <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
    <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New product_type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product_type.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @product_type.parent_id %>
</p>

<p>
  <b>Position:</b>
  <%= @product_type.position %>
</p>


<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>