config/routes.rb
Ashop::Application.routes.draw do
  resources :product_types

  resources :comments

  resources :prices

  resources :order_items

  resources :deliveries

  resources :ordered_products

  resources :sellers

  resources :incomming_orders

  resources :orders

  resources :customers

  resources :products

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment_id, :description, :product_id, :rating, :subject, :user_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :receiver_id, :state
end

app/models/incomming_order.rb
class IncommingOrder < ActiveRecord::Base
  attr_accessible :seller_id
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :description, :user_id
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :order_id, :position, :product_id
end

app/models/ordered_product.rb
class OrderedProduct < ActiveRecord::Base
  attr_accessible :name, :order_id
end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :active, :position, :price, :product_id
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :name, :parent_id, :position
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  attr_accessible :address, :name, :phone
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sellers }
    end
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @seller = Seller.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/new
  # GET /sellers/new.json
  def new
    @seller = Seller.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/1/edit
  def edit
    @seller = Seller.find(params[:id])
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(params[:seller])

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render json: @seller, status: :created, location: @seller }
      else
        format.html { render action: "new" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sellers/1
  # PUT /sellers/1.json
  def update
    @seller = Seller.find(params[:id])

    respond_to do |format|
      if @seller.update_attributes(params[:seller])
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller = Seller.find(params[:id])
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<h1>Listing sellers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sellers.each do |seller| %>
  <tr>
    <td><%= seller.name %></td>
    <td><%= seller.address %></td>
    <td><%= seller.phone %></td>
    <td><%= link_to 'Show', seller %></td>
    <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
    <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @seller.name %>
</p>

<p>
  <b>Address:</b>
  <%= @seller.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @seller.phone %>
</p>


<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>